const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, '..', 'frontend', 'src');
const backendDir = path.join(__dirname, '..', 'backend', 'app');

const dictionary = {
    // Basic Terms
    "Thanh toán": "Payment",
    "Món ăn": "Dish",
    "Bàn": "Table",
    "Khách hàng": "Customer",
    "Nhân viên": "Staff",
    "Đơn hàng": "Order",
    "Sản phẩm": "Product",
    "Danh mục": "Category",
    "Nguyên liệu": "Ingredient",
    "Biểu đồ": "Chart",
    "Đăng nhập": "Login",
    "Đăng xuất": "Logout",
    "Hủy": "Cancel",
    "Lưu": "Save",
    "Đóng": "Close",
    "Xác nhận": "Confirm",
    "Tìm kiếm": "Search",
    "Chi tiết": "Detail",
    "Tổng": "Total",
    "Giá": "Price",
    "Số lượng": "Quantity",
    "Thành tiền": "Amount",
    "Hành động": "Action",
    "Ngày": "Date",
    "Trạng thái": "Status",
    "Thành công": "Success",
    "Thêm": "Add",
    "Sửa": "Edit",
    "Xóa": "Delete",
    "Xem": "View",
    "Cập nhật": "Update",
    "Quay lại": "Back",
    "Tiếp tục": "Continue",
    "Tất cả": "All",
    "Hoạt động": "Active",
    "Tạm khóa": "Locked",
    "Không hoạt động": "Inactive",
    "Trống": "Empty",
    "Đã đặt": "Reserved",
    "Đang sử dụng": "In Use",
    "Hoàn thành": "Completed",
    "Đã hủy": "Cancelled",
    "Đã giao": "Delivered",
    "Đang chế biến": "Processing",
    "Đang gửi": "Sending",
    "Vui lòng": "Please",
    "Nhập": "Enter",
    "Chọn": "Select",
    "Địa chỉ": "Address",
    "Số điện thoại": "Phone",
    "Họ và tên": "Full Name",
    "Mô tả": "Description",
    "Đơn vị": "Unit",
    "Giá nhập": "Import Price",
    "Giá bán": "Selling Price",
    "Tồn kho": "Stock",
    "Cảnh báo": "Warning",
    "Thông báo": "Notification",
    "Báo cáo": "Report",
    "Doanh thu": "Revenue",
    "Quản lý": "Management",
    "Cấu hình": "Configuration",
    "Cài đặt": "Settings",
    "Hồ sơ": "Profile",
    "Tài khoản": "Account",
    "Mật khẩu": "Password",
    "Ghi chú": "Note",
    "Loại": "Type",
    "Món": "Dish",
    "Ảnh": "Image",
    "Tải": "Download",
    "Gửi": "Send",
    "Nhận": "Receive",
    "Trả": "Return",
    "Của": "of",
    "Và": "and",
    "Hoặc": "or",
    "Với": "with",
    "Từ": "from",
    "Đến": "to",

    // Detailed UI Terms
    "Thêm bàn mới": "Add New Table",
    "Số bàn": "Table No.",
    "Sức chứa": "Capacity",
    "Vị trí": "Location",
    "Tầng 1 trong nhà": "1st Floor Indoor",
    "Tầng 2 trong nhà": "2nd Floor Indoor",
    "Tầng 1 ngoài trời": "1st Floor Outdoor",
    "Tầng 2 ngoài trời": "2nd Floor Outdoor",
    "Tìm số bàn, mã đặt bàn...": "Search table, booking code...",
    "Không tìm thấy dữ liệu": "No data found",
    "Chi tiết đơn hàng": "Order Details",
    "Mã đặt": "Booking Code",
    "Lịch đặt bàn": "Booking Schedule",
    "Quản lý bàn": "Table Management",
    "Danh sách bàn": "Table List",
    "Tiếp theo": "Next",
    "Trang chủ": "Home",
    "Giỏ hàng": "Cart",
    "Tổng cộng": "Total",
    "Mã PIN": "PIN Code",
    "Tách hóa đơn": "Split Bill",
    "Gộp bàn": "Merge Table",
    "Chuyển bàn": "Transfer Table",
    "Thanh toán thành công": "Payment Successful",
    "Yêu cầu": "Request",
    "Chờ xác nhận": "Pending",
    "Đã xác nhận": "Confirmed",
    "Đã xong": "Ready",
    "Tiền mặt": "Cash",
    "Chuyển khoản": "Bank Transfer",
    "Mã giảm giá": "Coupon Code",
    "Giảm giá": "Discount",
    "Phí dịch vụ": "Service Fee",
    "Thuế": "Tax",
    "Tìm kiếm sản phẩm...": "Search products...",
    "Tìm kiếm danh mục...": "Search categories...",
    "Tìm kiếm nhân viên...": "Search staff...",
    "Tìm kiếm khách hàng...": "Search customers...",
    "Nhập số bàn": "Enter table number",
    "Nhập sức chứa": "Enter capacity",
    "Chọn vị trí": "Select location",
    "Có sẵn": "Available",
    "Bận": "Busy",
    "Khóa": "Locked",
    "Hành động": "Actions",
    "Ngày tạo": "Created At",
    "Ngày cập nhật": "Updated At",
    "Tên sản phẩm": "Product Name",
    "Tên danh mục": "Category Name",
    "Tên nhân viên": "Staff Name",
    "Vai trò": "Role",
    "Xác nhận mật khẩu": "Confirm Password",
    "Ảnh đại diện": "Avatar",
    "Ảnh sản phẩm": "Product Image",
    "Ảnh danh mục": "Category Image",
    "Cảnh báo tồn kho": "Stock Warning",
    "Hết hàng": "Out of Stock",
    "Đang bán": "On Sale",
    "Ngừng bán": "Discontinued",
    "VND": "VND",
    "₫": "VND",
    "đ": "VND",
    "Hệ thống": "System",
    "Tháng": "Month",
    "Năm": "Year",
    "Tuần": "Week",
    "Hôm nay": "Today",
    "Hôm qua": "Yesterday",
    "7 ngày qua": "Last 7 days",
    "30 ngày qua": "Last 30 days",
    "Thống kê": "Statistics",
    "Tổng đơn hàng": "Total Orders",
    "Tổng doanh thu": "Total Revenue",
    "Sản phẩm bán chạy": "Top Selling Products",
    "Đơn hàng gần đây": "Recent Orders",
    "Xem tất cả": "View All",
    "Ngôn ngữ": "Language",
    "Tiếng Việt": "Vietnamese",
    "Tiếng Anh": "English",
    "Chế độ sáng": "Light Mode",
    "Chế độ tối": "Dark Mode",
    "Vui lòng nhập": "Please enter",
    "Vui lòng chọn": "Please select",
    "Trường này là bắt buộc": "This field is required",
    "Đã gửi": "Sent",
    "Thử lại": "Try again",
    "Kết nối lại": "Reconnect",
    "Đã kết nối": "Connected",
    "Mất kết nối": "Disconnected",
    "Đang tải...": "Loading...",
    "Tìm kiếm...": "Searching...",
    "Thanh tìm kiếm": "Search bar",
    "Sắp xếp": "Sort",
    "Lọc": "Filter",
    "Áp dụng": "Apply",
    "Xóa bộ lọc": "Clear Filter",
    "Tách bàn": "Split Table",
    "Gỡ bàn": "Remove Table",
    "Mở rộng": "Expand",
    "Thu gọn": "Collapse",
    "Thêm vào giỏ hàng": "Add to Cart",
    "Mua ngay": "Buy Now",
    "Thanh toán khi nhận hàng": "COD",
    "Thanh toán trực tuyến": "Online Payment",
    "Cảm ơn bạn đã mua hàng!": "Thank you for your purchase!",
    "Đơn hàng của bạn đã được tiếp nhận.": "Your order has been received.",
    "Theo dõi đơn hàng": "Track Order",
    "Quay lại cửa hàng": "Back to Store",
    "Không có sản phẩm nào trong giỏ hàng.": "No products in cart.",
    "Tiếp tục mua sắm": "Continue Shopping",
    "Tiến hành thanh toán": "Proceed to Checkout",
    "Thông tin giao hàng": "Shipping Info",
    "Phương thức thanh toán": "Payment Method",
    "Tạm tính": "Subtotal",

    // Backend Messages
    "Không tìm thấy Admin": "Admin not found",
    "Nội dung không thể trống!": "Content cannot be empty!",
    "Không tìm thấy khách hàng với email": "Customer not found with email",
    "Không tìm thấy quản trị viên với email": "Admin not found with email",
    "Tài khoản của bạn đã bị khóa": "Your account has been locked",
    "Mật khẩu không chính xác.": "Incorrect password.",
    "Khách hàng đã tồn tại với email": "Customer already exists with email",
    "Quản trị viên đã tồn tại với email": "Admin already exists with email",
    "Xác nhận mật khẩu không khớp!": "Confirm password does not match!",
    "Thiếu dữ liệu": "Missing data",
    "Refresh token không hợp lệ.": "Invalid refresh token.",
    "User không tồn tại": "User does not exist",
    "Chỉ chấp nhận các định dạng ảnh: .jpg, .jpeg, .png": "Only .jpg, .jpeg, .png formats are accepted",
    "Cập nhật ảnh đại diện thành công": "Avatar updated successfully",
    "Lỗi khi lấy danh sách khách hàng": "Error getting customer list",
    "ID khách hàng không hợp lệ": "Invalid customer ID",
    "Không tìm thấy khách hàng": "Customer not found",
    "Lỗi khi lấy thông tin khách hàng": "Error getting customer info",
    "Cập nhật khách hàng thành công": "Customer updated successfully",
    "Khách": "Guest",
    "vãng lai": "walk-in",
    "tiền mặt": "cash",
    "chuyển khoản": "transfer"
};

function walkDir(dir, callback) {
    if (!fs.existsSync(dir)) return;
    fs.readdirSync(dir).forEach(f => {
        let dirPath = path.join(dir, f);
        let isDirectory = fs.statSync(dirPath).isDirectory();
        isDirectory ? walkDir(dirPath, callback) : callback(path.join(dir, f));
    });
}

const extensions = ['.jsx', '.js', '.scss', '.css'];

const sortedKeys = Object.keys(dictionary).sort((a, b) => b.length - a.length);

[srcDir, backendDir].forEach(dir => {
    walkDir(dir, (filePath) => {
        if (extensions.includes(path.extname(filePath))) {
            let content = fs.readFileSync(filePath, 'utf8');
            let originalContent = content;

            for (let key of sortedKeys) {
                const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
                const regex = new RegExp(escapedKey, 'g');
                content = content.replace(regex, dictionary[key]);
            }

            if (content !== originalContent) {
                fs.writeFileSync(filePath, content);
                console.log(`Translated: ${path.relative(path.join(__dirname, '..'), filePath)}`);
            }
        }
    });
});
